myproject/myapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create_new_superhero'),
    path('edit/<superhero_id>/', views.edit, name='edit_existing_superhero'),
    path('delete/<superhero_id>/', views.delete, name='delete_existing_superhero')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('', RedirectView.as_view(url='/myapp/'))
]

myproject/myapp/models.py
from django.db import models

# Create your models here.
class Superheroes(models.Model):
    superhero_name = models.CharField(max_length=50)
    alter_ego_name = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.superhero_name
    
    

myproject/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superheroes
# Create your views here.


def index(request):
    all_superheroes = Superheroes.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'myapp/index.html', context)

def detail(request, superhero_id):
    superhero = Superheroes.objects.get(pk=superhero_id)
    context = {
        'superhero': superhero
    }

    return render(request, 'myapp/details.html', context)

def create(request):
    if request.method == 'POST':
        superhero_name = request.POST.get('name')
        alter_ego_name = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catch_phrase = request.POST.get('catchphrase')
        new_superhero = Superheroes(
            superhero_name = superhero_name, 
            alter_ego_name = alter_ego_name, 
            primary_ability = primary_ability, 
            secondary_ability = secondary_ability, 
            catch_phrase = catch_phrase
        )
        new_superhero.save()
        return HttpResponseRedirect(reverse('myapp:index'))
    else:
        return render(request, 'myapp/create.html')

def edit(request, superhero_id):
    superhero = Superheroes.objects.get(pk=superhero_id)
    if request.method == "POST":
        superhero.superhero_name = request.POST.get('name')
        superhero.alter_ego_name = request.POST.get('alter_ego')
        superhero.primary_ability = request.POST.get('primary_ability')
        superhero.secondary_ability = request.POST.get('secondary_ability')
        superhero.catchphrase = request.POST.get('catchphrase')
        superhero.save()
        context = {
            "superhero": superhero
        }
        return render(request, 'myapp/details.html', context)
    else:
        context = {
            "superhero": superhero
        }
        return render(request, 'myapp/edit.html', context)

def delete(request, superhero_id):
    superhero = Superheroes.objects.get(pk=superhero_id)
    if request.method == "POST":
        superhero.delete()
        return HttpResponseRedirect(reverse('myapp:index'))
    else:
        context = {
            "superhero": superhero
        }
        return render(request, 'myapp/delete.html', context)

myproject/myapp/templates/myapp/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CREATE!</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>



  <div class="container-fluid">
      <div class="row">
          <div class="heading col-sm-12">
            <h1>Create a new superhero!</h1>
          </div>


          <div class="Lblank col-sm-1"></div>





          <div class="L col col-sm-5">
            <form action="{% url 'myapp:create_new_superhero' %}" method="post">
              {% csrf_token %} <br />
              <p>Fill out this form!</p>
              Name: <br><input 
                type="text" 
                name="name" 
                id="name" 
                /><br />

              Alter ego: <input 
                type="text" 
                name="alter_ego" 
                id="alter_ego" 
                /><br />

              Primary ability:<input
                type="text"
                name="primary_ability"
                id="primary_ability"
              /><br />

              Secondary ability:<input
                type="text"
                name="secondary_ability"
                id="secondary_ability"
              /><br />

              Catchphrase:
              <input type="text" name="catchphrase" id="catchphrase" /><br /><br>
              <input type="submit" value="Add new!" />
              <a href="{% url 'myapp:index' %}" class="btn btn-primary">Home</a>
            </form>
          </div>


          <div class="R col col-sm-5">
          {% load static %}
          <img src="{% static 'myapp/avengers.jpg' %}" alt="joker" class="container-fluid"></img>
          </div>







          <div class="Rblank col-sm-1"></div>
      </div>
  </div>







  
      



    







  </body>
</html>

myproject/myapp/templates/myapp/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>remove</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
</head>
<body>
    <h1 class="containter-fluid"> Are you sure you want to delete {{selected_hero.name}}? </h1>

    <form action="{% url 'myapp:detail' superhero.id %}" method="get">

        {% csrf_token %}

        <input type="submit" value="Cancel" class="btn btn-primary">
    </form>


    <form action="{% url 'myapp:delete_existing_superhero' superhero.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>

    
</body>
</html>

myproject/myapp/templates/myapp/details.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>deetz</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>





    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-12">
            <h1>Hero details</h1>
          </div>







          {% load static %}
          <img src="{% static 'myapp/justiceleague.jpg' %}" alt="joker" class="container-fluid"></img>



          <h1 class="container">{{superhero.superhero_name}}</h1>
              <ul>
                <li class="list-group-item">Alter ego: {{superhero.alter_ego_name}}</li>
                <li class="list-group-item">Primary ability:{{superhero.primary_ability}}</li>
                <li class="list-group-item">Secondary ability:{{superhero.secondary_ability}}</li>
                <li class="list-group-item">Catchphrase{{superhero.catch_phrase}}</li>

              </ul>

              

              <div class="container-fluid">
              <a href="{% url 'myapp:edit_existing_superhero' superhero.id %}" class="btn btn-primary">Edit Superhero</a>


              <a href="{% url 'myapp:delete_existing_superhero' superhero.id %}" class="btn btn-primary">Delete Superhero</a>
              
              <a href="{% url 'myapp:index' %}" class="btn btn-primary">Home</a>
    
          </div>








      </div>
    </div>












    


    
  </body>
</html>

myproject/myapp/templates/myapp/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>edit</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>


  <body>




    <div class="container">

      <div class="row">
          <div class="col-sm-6">
                  <h1 class="container-fluid">Edit your superhero!</h1>
                  <br>
                  {% load static %}
                  <img src="{% static 'myapp/wham.jpg' %}" alt="joker" class="container-fluid"></img>
                  <form
                    action="{% url 'myapp:edit_existing_superhero' superhero.id %}"
                    method="post"
                  >
                    {% csrf_token %} <br />
                    
                    Name: <br><input 
                      type="text" 
                      name="name" 
                      id="name" 
                      value="{{superhero.superhero_name}}"

                      /><br />
                    
                    Alter ego:
                    <input
                      type="text"
                      name="alter_ego"
                      id="alter_ego"
                      value="{{superhero.alter_ego_name}}"
                    /><br />
                    
                    Primary ability:<input
                      type="text"
                      name="primary_ability"
                      id="primary_ability"
                      value="{{superhero.primary_ability}}"

                    /><br />
                    
                    Secondary ability:<input
                      type="text"
                      name="secondary_ability"
                      id="secondary_ability"
                      value="{{superhero.secondary_ability}}"

                    /><br />
                    
                    Catchphrase:
                    <input 
                      type="text" 
                      name="catchphrase" 
                      id="catchphrase" 
                      value="{{superhero.catch_phrase}}"


                      /><br />

              <input type="submit" value="Edit your hero!" />
              <a href="{% url 'myapp:index' %}" class="btn btn-primary">Home</a>

            </form>
          </div>










          <div class="col-sm-6">
        
      </div>
    </div>








    
  </body>
</html>

{% comment %} <h2>{{superhero.superhero_name}}</h2>
    <h2>{{superhero.alter_ego_name}}</h2>
    <h2>{{superhero.primary_ability}}</h2>
    <h2>{{superhero.secondary_ability}}</h2>
    <h2>{{superhero.catch_phrase}}</h2> {% endcomment %}

myproject/myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Superheroes index?</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>


  <body>
    <h1 class="container-fluid">Hello, Superheroes maybe? YES!</h1>
    
    <br>



    <a href="{% url 'myapp:create_new_superhero' %}" class="btn btn-primary">Create your own superhero!</a>





    {% load static %}
    <img src="{% static 'myapp/joker.jpeg' %}" alt="joker" class="container-fluid"></img>




    <br>
    <h3>check out existing superheroes!</h3>
    <br>


    <ul class="list-group list-group-flush">
      {% for hero in all_superheroes %}
      <li>
        <h2>{{hero.superhero_name}}</h2>
        <a href="{% url 'myapp:detail' hero.id %}" class="btn btn-primary">more info</a>

      </li>
      {% endfor %}
    </ul>


  </body>
</html>